### PR TITLE
Adding custom phase length options for WiggleRate and ShakeRate

### PR DESCRIPTION
**Pull request by mergesort**
This addresses #30, and adds the same functionality for ShakeRate.

### CODE REVIEW

**Comment by 0xifarouk** [comment]
@robb any thoughts?

**Comment by mergesort** [comment]
Oh sorry, I'm actually the maintainer of Pow now but I've haven't gotten around to merging it in because I've been testing it in my own app before making an official release. 😅

I'll probably merge it in over the next week or two, but if you need it sooner let me know!

**Comment by 0xifarouk** [comment]
@mergesort No worries take your time.
I tried it locally but it didn't give me the desired outcome I wanted.
If there is a way to wiggle less (lower the wiggle rotation angle) so it wiggles very very gently.

**Comment by mergesort** [comment]
Would you be able to show me the code you've tried to slow things down? When it comes to how the animation looks,, wiggle rate and the animation speed/timing.

In my case I was looking to speed up my animation, and was able to do so by lowering the phase length and increasing the animation timing. This is just an example, but you should be able to tweak the numbers and see if it works for you.

```swift
.changeEffect(
    .shake(rate: .phaseLength(0.2)),
    value: self.saveState,
    isEnabled: self.saveState == .error
)
.animation(.easeInOut(duration: 0.15), value: self.saveState)
```

Let me know if that works!

**Pull request merged**
